-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: db
-- Generation Time: Jun 24, 2020 at 07:05 PM
-- Server version: 5.7.30
-- PHP Version: 7.4.5

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `edtech_csf`
--

-- --------------------------------------------------------

--
-- Table structure for table `TeacherRecords`
--

CREATE TABLE `TeacherRecords` (
  `id` int(11) UNSIGNED NOT NULL,
  `content_title` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `content_description` varchar(500) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `content_link` varchar(4000) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `use_case` int(5) NOT NULL,
  `cost` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `device` int(3) NOT NULL DEFAULT '0',
  `medium` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `language` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `TeacherRecords`
--

INSERT INTO `TeacherRecords` (`id`, `content_title`, `content_description`, `content_link`, `use_case`, `cost`, `device`, `medium`, `language`) VALUES
(1, 'DIKSHA', 'DIKSHA has very engaging content (activities, assessments, videos, worksheets, songs) for you to use as is or build into your lesson plans. Its a huge library of excellent resources you can use to make your classess, assessments more engaging and fun!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 1, 'Free', 1, 'English', 'EN'),
(2, 'DIKSHA', 'DIKSHA has very engaging content (activities, assessments, videos, worksheets, songs) for you to use as is or build into your lesson plans. Its a huge library of excellent resources you can use to make your classess, assessments more engaging and fun!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 1, 'Free', 1, 'Hindi', 'EN'),
(3, 'DIKSHA', 'DIKSHA has very engaging content (activities, assessments, videos, worksheets, songs) for you to use as is or build into your lesson plans. Its a huge library of excellent resources you can use to make your classess, assessments more engaging and fun!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 1, 'Free', 1, 'Tamil', 'EN'),
(4, 'DIKSHA', 'DIKSHA has very engaging content (activities, assessments, videos, worksheets, songs) for you to use as is or build into your lesson plans. Its a huge library of excellent resources you can use to make your classess, assessments more engaging and fun!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 1, 'Free', 1, 'Telugu', 'EN'),
(5, 'DIKSHA', 'DIKSHA has very engaging content (activities, assessments, videos, worksheets, songs) for you to use as is or build into your lesson plans. Its a huge library of excellent resources you can use to make your classess, assessments more engaging and fun!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 1, 'Free', 1, 'Marathi', 'EN'),
(6, 'DIKSHA', 'DIKSHA has very engaging content (activities, assessments, videos, worksheets, songs) for you to use as is or build into your lesson plans. Its a huge library of excellent resources you can use to make your classess, assessments more engaging and fun!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 2, 'Free', 1, 'English', 'EN'),
(7, 'DIKSHA', 'DIKSHA has very engaging content (activities, assessments, videos, worksheets, songs) for you to use as is or build into your lesson plans. Its a huge library of excellent resources you can use to make your classess, assessments more engaging and fun!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 2, 'Free', 1, 'Hindi', 'EN'),
(8, 'DIKSHA', 'DIKSHA has very engaging content (activities, assessments, videos, worksheets, songs) for you to use as is or build into your lesson plans. Its a huge library of excellent resources you can use to make your classess, assessments more engaging and fun!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 2, 'Free', 1, 'Tamil', 'EN'),
(9, 'DIKSHA', 'DIKSHA has very engaging content (activities, assessments, videos, worksheets, songs) for you to use as is or build into your lesson plans. Its a huge library of excellent resources you can use to make your classess, assessments more engaging and fun!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 2, 'Free', 1, 'Telugu', 'EN'),
(10, 'DIKSHA', 'DIKSHA has very engaging content (activities, assessments, videos, worksheets, songs) for you to use as is or build into your lesson plans. Its a huge library of excellent resources you can use to make your classess, assessments more engaging and fun!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 2, 'Free', 1, 'Marathi', 'EN'),
(11, 'DIKSHA', 'DIKSHA has very engaging content (activities, assessments, videos, worksheets, songs) for you to use as is or build into your lesson plans. Its a huge library of excellent resources you can use to make your classess, assessments more engaging and fun!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 3, 'Free', 1, 'English', 'EN'),
(12, 'DIKSHA', 'DIKSHA has very engaging content (activities, assessments, videos, worksheets, songs) for you to use as is or build into your lesson plans. Its a huge library of excellent resources you can use to make your classess, assessments more engaging and fun!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 3, 'Free', 1, 'Hindi', 'EN'),
(13, 'DIKSHA', 'DIKSHA has very engaging content (activities, assessments, videos, worksheets, songs) for you to use as is or build into your lesson plans. Its a huge library of excellent resources you can use to make your classess, assessments more engaging and fun!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 3, 'Free', 1, 'Tamil', 'EN'),
(14, 'DIKSHA', 'DIKSHA has very engaging content (activities, assessments, videos, worksheets, songs) for you to use as is or build into your lesson plans. Its a huge library of excellent resources you can use to make your classess, assessments more engaging and fun!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 3, 'Free', 1, 'Telugu', 'EN'),
(15, 'DIKSHA', 'DIKSHA has very engaging content (activities, assessments, videos, worksheets, songs) for you to use as is or build into your lesson plans. Its a huge library of excellent resources you can use to make your classess, assessments more engaging and fun!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 3, 'Free', 1, 'Marathi', 'EN'),
(16, 'Teacher App', 'A platform where you can access high quality content in Hindi to learn and grow yourself. You get access to courses, educational resources for your classes, stories and conversations from different parts of India.', 'https://play.google.com/store/apps/details?id=org.tta.mobile,https://play.google.com/store/apps/details?id=org.tta.mobile', 2, 'Free', 1, 'Hindi', 'EN'),
(17, 'Google Classroom', 'You can create online classrooms, ask students to attend your class, and create and give out assignments. You can communicate about the assignments within the platform and monitor students’ progress. Schools can create a free Google Apps for Education account to utilize this solution.', 'https://edu.google.com/products/classroom/?modal_active=none,https://play.google.com/store/apps/details?id=com.google.android.apps.classroom&hl=en_IN', 1, 'Free', 3, 'English', 'EN'),
(18, 'Google Classroom', 'You can create online classrooms, ask students to attend your class, and create and give out assignments. You can communicate about the assignments within the platform and monitor students’ progress. Schools can create a free Google Apps for Education account to utilize this solution.', 'https://edu.google.com/products/classroom/?modal_active=none,https://play.google.com/store/apps/details?id=com.google.android.apps.classroom&hl=en_IN', 3, 'Free', 3, 'English', 'EN'),
(19, 'Ted Ed', 'The TED-Ed platform allows you to take any TED Talk, TED-Ed Lesson or educational video (from youtube) and easily create a lesson plan of customized questions and discussions. You can then distribute these lessons and have your students engage and respond!', 'https://ed.ted.com/,https://ed.ted.com/', 1, 'Free', 2, 'English', 'EN'),
(20, 'Kahoot', 'An easy to use platform that allows you to create a learning game or quiz for your students in few minutes - on any topic and in any language. You can either host games or assessments live over any platform or assign them for students to do at home. Answers are automatically assessed.', 'https://create.kahoot.it/register/sign-up-options?accountType=teacher&plan=premium12nocct_schools&next=%2Fregister%2Fupgrade-confirm,https://play.google.com/store/apps/details?id=no.mobitroll.kahoot.android&hl=en_IN', 3, 'Free', 3, 'English', 'EN'),
(21, 'Padlet', 'Padlet is like a chartpaper for your screen. Start with an empty page and then put material on it to collaborate with your class. Upload a video and ask for students to upload theirs, record an interview and get students to ask questions, snap a selfie, write your own posts its or upload some documents. You can post whatever you like and help your students collaborate, discuss and reflect during your classes or as homework!', 'https://padlet.com/auth/signup,https://play.google.com/store/apps/details?id=com.wallwisher.Padlet&hl=en_IN', 1, 'Free', 3, 'English', 'EN'),
(22, 'Wizer Me', 'You can create worksheets with audio, video, images and a variety of question types. You can quickly assign the worksheets to your students and they will be automatically checked and graded or you can give more personalised feedback if you like! There\'s also a cllection of free resources that other teachers have put up that you can modify and use as you like.', 'https://app.wizer.me/signup,https://app.wizer.me/signup', 1, 'Free', 2, 'English', 'EN'),
(23, 'Quizizz', 'You can quickly create or use existiitng assessments and quizes for your students. You can conduct it live or assign it as homework for students to practive. Very easy to read, insightful reports are available automatically too.', 'https://quizizz.com/join,https://play.google.com/store/apps/details?id=com.quizizz_mobile&hl=en_IN', 3, 'Free', 3, 'English', 'EN'),
(24, 'Meghshala', 'A curriculum alligned, multi lingual app that will give you ready made lesson plans that you can use to take your classes over the internet.', 'https://play.google.com/store/apps/details?id=online.meghshala.app&hl=en_IN,https://play.google.com/store/apps/details?id=online.meghshala.app&hl=en_IN', 1, 'Free', 1, 'Kannada', 'EN'),
(25, 'Meghshala', 'A curriculum alligned, multi lingual app that will give you ready made lesson plans that you can use to take your classes over the internet.', 'https://play.google.com/store/apps/details?id=online.meghshala.app&hl=en_IN,https://play.google.com/store/apps/details?id=online.meghshala.app&hl=en_IN', 1, 'Free', 1, 'Hindi', 'EN'),
(26, 'Meghshala', 'A curriculum alligned, multi lingual app that will give you ready made lesson plans that you can use to take your classes over the internet.', 'https://play.google.com/store/apps/details?id=online.meghshala.app&hl=en_IN,https://play.google.com/store/apps/details?id=online.meghshala.app&hl=en_IN', 1, 'Free', 1, 'English', 'EN'),
(27, 'Meghshala', 'A curriculum alligned, multi lingual app that will give you ready made lesson plans that you can use to take your classes over the internet.', 'https://play.google.com/store/apps/details?id=online.meghshala.app&hl=en_IN,https://play.google.com/store/apps/details?id=online.meghshala.app&hl=en_IN', 2, 'Free', 1, 'Kannada', 'EN'),
(28, 'Meghshala', 'A curriculum alligned, multi lingual app that will give you ready made lesson plans that you can use to take your classes over the internet.', 'https://play.google.com/store/apps/details?id=online.meghshala.app&hl=en_IN,https://play.google.com/store/apps/details?id=online.meghshala.app&hl=en_IN', 2, 'Free', 1, 'Hindi', 'EN'),
(29, 'Meghshala', 'A curriculum alligned, multi lingual app that will give you ready made lesson plans that you can use to take your classes over the internet.', 'https://play.google.com/store/apps/details?id=online.meghshala.app&hl=en_IN,https://play.google.com/store/apps/details?id=online.meghshala.app&hl=en_IN', 2, 'Free', 1, 'English', 'EN'),
(30, 'TCS iON Digital Glass Room', 'A platform that allows you to conduct live virtual classes with your students. Assign homework and assessments to students as well as provide feedback, resolve doubts.', 'https://learning.tcsionhub.in//EForms/configuredHtml/1016/65312/Registration.html,https://learning.tcsionhub.in//EForms/configuredHtml/1016/65312/Registration.html', 1, 'Free', 2, 'English', 'EN'),
(31, 'TCS iON Digital Glass Room', 'A platform that allows you to conduct live virtual classes with your students. Assign homework and assessments to students as well as provide feedback, resolve doubts.', 'https://learning.tcsionhub.in//EForms/configuredHtml/1016/65312/Registration.html,https://learning.tcsionhub.in//EForms/configuredHtml/1016/65312/Registration.html', 3, 'Free', 2, 'English', 'EN'),
(32, 'Nishtha', 'Nishtha is a capacity building tool that aims to build competencies among all the teachers and school principals via an integrated training method that uses activity-based training modules.', 'https://play.google.com/store/apps/details?id=ncert.ciet.nishtha&hl=en_US,https://itpd.ncert.gov.in//', 2, 'Free', 3, 'English', 'EN'),
(33, 'IDP EdTech IIT Bombay', 'A repository of simple technology tools and how-to videos to assist and support teachers in the transition to digital teaching and learning.', 'http://www.et.iitb.ac.in/online-Teaching.html,http://www.et.iitb.ac.in/online-Teaching.html', 1, 'Free', 1, 'English', 'EN'),
(34, 'IDP EdTech IIT Bombay', 'A repository of simple technology tools and how-to videos to assist and support teachers in the transition to digital teaching and learning.', 'http://www.et.iitb.ac.in/online-Teaching.html,http://www.et.iitb.ac.in/online-Teaching.html', 3, 'Free', 1, 'English', 'EN'),
(35, 'दीक्षा', 'दीक्षा के पास बहुत ही आकर्षक कंटेंट है (गतिविधियाँ, परीक्षाएं , वीडियो, कार्यपत्रक और गीत) जो आप सीधा इस्तेमाल कर सकते हैं या अपनी पाठ योजनाओं में इन्हें डाल सकते हैं। इसके विशाल पुस्तकालय का उपयोग आप अपनी कक्षा और अभ्यास परीक्षाओं को ज़्यादा आकर्षक और मजेदार बनाने के लिए कर सकते हैं!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 1, 'मुफ्त', 1, 'अंग्रेजी', 'HI'),
(36, 'दीक्षा', 'दीक्षा के पास बहुत ही आकर्षक कंटेंट है (गतिविधियाँ, परीक्षाएं , वीडियो, कार्यपत्रक और गीत) जो आप सीधा इस्तेमाल कर सकते हैं या अपनी पाठ योजनाओं में इन्हें डाल सकते हैं। इसके विशाल पुस्तकालय का उपयोग आप अपनी कक्षा और अभ्यास परीक्षाओं को ज़्यादा आकर्षक और मजेदार बनाने के लिए कर सकते हैं!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 1, 'मुफ्त', 1, 'हिंदी', 'HI'),
(37, 'दीक्षा', 'दीक्षा के पास बहुत ही आकर्षक कंटेंट है (गतिविधियाँ, परीक्षाएं , वीडियो, कार्यपत्रक और गीत) जो आप सीधा इस्तेमाल कर सकते हैं या अपनी पाठ योजनाओं में इन्हें डाल सकते हैं। इसके विशाल पुस्तकालय का उपयोग आप अपनी कक्षा और अभ्यास परीक्षाओं को ज़्यादा आकर्षक और मजेदार बनाने के लिए कर सकते हैं!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 1, 'मुफ्त', 1, 'तमिल', 'HI'),
(38, 'दीक्षा', 'दीक्षा के पास बहुत ही आकर्षक कंटेंट है (गतिविधियाँ, परीक्षाएं , वीडियो, कार्यपत्रक और गीत) जो आप सीधा इस्तेमाल कर सकते हैं या अपनी पाठ योजनाओं में इन्हें डाल सकते हैं। इसके विशाल पुस्तकालय का उपयोग आप अपनी कक्षा और अभ्यास परीक्षाओं को ज़्यादा आकर्षक और मजेदार बनाने के लिए कर सकते हैं!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 1, 'मुफ्त', 1, 'तेलुगु', 'HI'),
(39, 'दीक्षा', 'दीक्षा के पास बहुत ही आकर्षक कंटेंट है (गतिविधियाँ, परीक्षाएं , वीडियो, कार्यपत्रक और गीत) जो आप सीधा इस्तेमाल कर सकते हैं या अपनी पाठ योजनाओं में इन्हें डाल सकते हैं। इसके विशाल पुस्तकालय का उपयोग आप अपनी कक्षा और अभ्यास परीक्षाओं को ज़्यादा आकर्षक और मजेदार बनाने के लिए कर सकते हैं!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 1, 'मुफ्त', 1, 'मराठी', 'HI'),
(40, 'दीक्षा', 'दीक्षा के पास बहुत ही आकर्षक कंटेंट है (गतिविधियाँ, परीक्षाएं , वीडियो, कार्यपत्रक और गीत) जो आप सीधा इस्तेमाल कर सकते हैं या अपनी पाठ योजनाओं में इन्हें डाल सकते हैं। इसके विशाल पुस्तकालय का उपयोग आप अपनी कक्षा और अभ्यास परीक्षाओं को ज़्यादा आकर्षक और मजेदार बनाने के लिए कर सकते हैं!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 2, 'मुफ्त', 1, 'अंग्रेजी', 'HI'),
(41, 'दीक्षा', 'दीक्षा के पास बहुत ही आकर्षक कंटेंट है (गतिविधियाँ, परीक्षाएं , वीडियो, कार्यपत्रक और गीत) जो आप सीधा इस्तेमाल कर सकते हैं या अपनी पाठ योजनाओं में इन्हें डाल सकते हैं। इसके विशाल पुस्तकालय का उपयोग आप अपनी कक्षा और अभ्यास परीक्षाओं को ज़्यादा आकर्षक और मजेदार बनाने के लिए कर सकते हैं!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 2, 'मुफ्त', 1, 'हिंदी', 'HI'),
(42, 'दीक्षा', 'दीक्षा के पास बहुत ही आकर्षक कंटेंट है (गतिविधियाँ, परीक्षाएं , वीडियो, कार्यपत्रक और गीत) जो आप सीधा इस्तेमाल कर सकते हैं या अपनी पाठ योजनाओं में इन्हें डाल सकते हैं। इसके विशाल पुस्तकालय का उपयोग आप अपनी कक्षा और अभ्यास परीक्षाओं को ज़्यादा आकर्षक और मजेदार बनाने के लिए कर सकते हैं!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 2, 'मुफ्त', 1, 'तमिल', 'HI'),
(43, 'दीक्षा', 'दीक्षा के पास बहुत ही आकर्षक कंटेंट है (गतिविधियाँ, परीक्षाएं , वीडियो, कार्यपत्रक और गीत) जो आप सीधा इस्तेमाल कर सकते हैं या अपनी पाठ योजनाओं में इन्हें डाल सकते हैं। इसके विशाल पुस्तकालय का उपयोग आप अपनी कक्षा और अभ्यास परीक्षाओं को ज़्यादा आकर्षक और मजेदार बनाने के लिए कर सकते हैं!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 2, 'मुफ्त', 1, 'तेलुगु', 'HI'),
(44, 'दीक्षा', 'दीक्षा के पास बहुत ही आकर्षक कंटेंट है (गतिविधियाँ, परीक्षाएं , वीडियो, कार्यपत्रक और गीत) जो आप सीधा इस्तेमाल कर सकते हैं या अपनी पाठ योजनाओं में इन्हें डाल सकते हैं। इसके विशाल पुस्तकालय का उपयोग आप अपनी कक्षा और अभ्यास परीक्षाओं को ज़्यादा आकर्षक और मजेदार बनाने के लिए कर सकते हैं!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 2, 'मुफ्त', 1, 'मराठी', 'HI'),
(45, 'दीक्षा', 'दीक्षा के पास बहुत ही आकर्षक कंटेंट है (गतिविधियाँ, परीक्षाएं , वीडियो, कार्यपत्रक और गीत) जो आप सीधा इस्तेमाल कर सकते हैं या अपनी पाठ योजनाओं में इन्हें डाल सकते हैं। इसके विशाल पुस्तकालय का उपयोग आप अपनी कक्षा और अभ्यास परीक्षाओं को ज़्यादा आकर्षक और मजेदार बनाने के लिए कर सकते हैं!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 3, 'मुफ्त', 1, 'अंग्रेजी', 'HI'),
(46, 'दीक्षा', 'दीक्षा के पास बहुत ही आकर्षक कंटेंट है (गतिविधियाँ, परीक्षाएं , वीडियो, कार्यपत्रक और गीत) जो आप सीधा इस्तेमाल कर सकते हैं या अपनी पाठ योजनाओं में इन्हें डाल सकते हैं। इसके विशाल पुस्तकालय का उपयोग आप अपनी कक्षा और अभ्यास परीक्षाओं को ज़्यादा आकर्षक और मजेदार बनाने के लिए कर सकते हैं!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 3, 'मुफ्त', 1, 'हिंदी', 'HI'),
(47, 'दीक्षा', 'दीक्षा के पास बहुत ही आकर्षक कंटेंट है (गतिविधियाँ, परीक्षाएं , वीडियो, कार्यपत्रक और गीत) जो आप सीधा इस्तेमाल कर सकते हैं या अपनी पाठ योजनाओं में इन्हें डाल सकते हैं। इसके विशाल पुस्तकालय का उपयोग आप अपनी कक्षा और अभ्यास परीक्षाओं को ज़्यादा आकर्षक और मजेदार बनाने के लिए कर सकते हैं!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 3, 'मुफ्त', 1, 'तमिल', 'HI'),
(48, 'दीक्षा', 'दीक्षा के पास बहुत ही आकर्षक कंटेंट है (गतिविधियाँ, परीक्षाएं , वीडियो, कार्यपत्रक और गीत) जो आप सीधा इस्तेमाल कर सकते हैं या अपनी पाठ योजनाओं में इन्हें डाल सकते हैं। इसके विशाल पुस्तकालय का उपयोग आप अपनी कक्षा और अभ्यास परीक्षाओं को ज़्यादा आकर्षक और मजेदार बनाने के लिए कर सकते हैं!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 3, 'मुफ्त', 1, 'तेलुगु', 'HI'),
(49, 'दीक्षा', 'दीक्षा के पास बहुत ही आकर्षक कंटेंट है (गतिविधियाँ, परीक्षाएं , वीडियो, कार्यपत्रक और गीत) जो आप सीधा इस्तेमाल कर सकते हैं या अपनी पाठ योजनाओं में इन्हें डाल सकते हैं। इसके विशाल पुस्तकालय का उपयोग आप अपनी कक्षा और अभ्यास परीक्षाओं को ज़्यादा आकर्षक और मजेदार बनाने के लिए कर सकते हैं!', 'https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN,https://play.google.com/store/apps/details?id=in.gov.diksha.app&hl=en_IN', 3, 'मुफ्त', 1, 'मराठी', 'HI'),
(50, 'टीचर ऐप', 'एक ऐसा मंच जहाँ आप अपने आप को सिखाने और विकसित करने के लिए हिंदी में उच्च गुणवत्ता की सामग्री का इस्तेमाल कर सकते हैं। आप भारत के विभिन्न हिस्सों से अपनी कक्षाओं, कहानियों और वार्तालापों के लिए पाठ्यक्रम, शैक्षिक संसाधनों तक पहुँच प्राप्त कर सकते हैं।', 'https://play.google.com/store/apps/details?id=org.tta.mobile,https://play.google.com/store/apps/details?id=org.tta.mobile', 2, 'मुफ्त', 1, 'हिन्दी', 'HI'),
(51, 'गूगल क्लासरूम', 'आप ऑनलाइन क्लासरूम बना सकते हैं, छात्रों को अपनी कक्षा में भाग लेने के लिए कह सकते हैं, और असाइनमेंट दे सकते हैं। आप एप के भीतर से ही असाइनमेंट के बारे में संवाद कर सकते हैं और छात्रों की प्रगति की निगरानी कर सकते हैं। स्कूल इस समाधान का उपयोग करने के लिए शिक्षा खाते के लिए एक मुफ्त गूगल एप भी बनवा सकते है ।', 'https://edu.google.com/products/classroom/?modal_active=none,https://play.google.com/store/apps/details?id=com.google.android.apps.classroom&hl=en_IN', 1, 'मुफ्त', 3, 'अंग्रेज़ी', 'HI'),
(52, 'गूगल क्लासरूम', 'आप ऑनलाइन क्लासरूम बना सकते हैं, छात्रों को अपनी कक्षा में भाग लेने के लिए कह सकते हैं, और असाइनमेंट दे सकते हैं। आप एप के भीतर से ही असाइनमेंट के बारे में संवाद कर सकते हैं और छात्रों की प्रगति की निगरानी कर सकते हैं। स्कूल इस समाधान का उपयोग करने के लिए शिक्षा खाते के लिए एक मुफ्त गूगल एप भी बनवा सकते है ।', 'https://edu.google.com/products/classroom/?modal_active=none,https://play.google.com/store/apps/details?id=com.google.android.apps.classroom&hl=en_IN', 3, 'मुफ्त', 3, 'अंग्रेज़ी', 'HI'),
(53, 'टेड एड', 'टेड-एड प्लेटफ़ॉर्म आपको किसी भी टेड टॉक, टेड-एड लेसन या शैक्षिक वीडियो (यूट्यूब से) लेने की अनुमति देता है और आप आसानी से इच्छा अनुसार प्रश्नों और चर्चाओं की एक पाठ योजना बना सकते हैं। फिर आप इन पाठों को बाट सकते हैं और अपने छात्रों से जुड़, इनका जवाब दे सकते है', 'https://ed.ted.com/,https://ed.ted.com/', 1, 'मुफ्त', 2, 'अंग्रेज़ी', 'HI'),
(54, 'काहूत', 'एक आसानी से इस्तेमाल किए जाने वाला मंच जो आपको कुछ ही मिनटों में - किसी भी विषय पर और किसी भी भाषा, में अपने छात्रों के लिए सिखाने वाले खेल या प्रश्नोत्तरी बनाने की अनुमति देता है। आप खेल या परीक्षाएं भी मंच पर डाल सकते हैं या उन्हें घर पर छात्रों के लिए दे सकते हैं। उत्तरों का आटोमेटिक स्कोरिंग भी किया जा सकता है', 'https://create.kahoot.it/register/sign-up-options?accountType=teacher&plan=premium12nocct_schools&next=%2Fregister%2Fupgrade-confirm,https://play.google.com/store/apps/details?id=no.mobitroll.kahoot.android&hl=en_IN', 3, 'मुफ्त', 3, 'अंग्रेज़ी', 'HI'),
(55, 'पैडलैट', 'पैडलेट आपकी स्क्रीन के लिए एक चार्टपेपर की तरह है। एक खाली पन्ने से शुरू करें और फिर अपनी कक्षा के साथ बात चीत करने के लिए उस पर लिखें। वीडियो अपलोड करें और छात्रों से उनकी विडियोअपलोड करने के लिए कहें, इंटरव्यू रिकॉर्ड करें और छात्रों को सवाल पूछने को कहें, सेल्फी लें, अपनी खुद के पोस्ट लिखें या कुछ लिखित अपलोड करें। आप जो चाहें पोस्ट कर सकते हैं और अपने छात्रों को सहयोग करने, चर्चा करने और अपनी कक्षाओं के दौरान या होमवर्क के दौरान विचार करने में मदद कर सकते हैं!', 'https://padlet.com/auth/signup,https://play.google.com/store/apps/details?id=com.wallwisher.Padlet&hl=en_IN', 1, 'मुफ्त', 3, 'अंग्रेज़ी', 'HI'),
(56, 'वाइजर मी', 'आप ऑडियो, वीडियो, चित्र और विभिन्न प्रकार के प्रश्न के साथ वर्कशीट बना सकते हैं। आप अपने छात्रों को वर्कशीट जल्दी से सौंप सकते हैं और उनकी अपने आप चेकिंग और स्कोरिंग हो जाएंगे | इसके अलावा आप चाहें तो अपने इच्छा अनुसार टिप्पणी दे सकते हैं! आप अन्य शिक्षकों से बनाये गयी चीज़ो का भी उपयोग कर सकते है |', 'https://app.wizer.me/signup,https://app.wizer.me/signup', 1, 'मुफ्त', 2, 'अंग्रेज़ी', 'HI'),
(57, 'कुईज़्ज़िज्ज', 'आप अपने छात्रों के लिए जल्दी से पहले से बानी हुई परीक्षा और प्रश्नोत्तरी का उपयोग कर सकते हैं या खुद बना सकते हैं। आप इसे लाइव कर सकते हैं या छात्रों को अभ्यास के लिए इसे होमवर्क के रूप में दे सकते हैं। पढ़ने में बहुत आसान, व्यावहारिक रिपोर्ट भी उपलब्ध हैं इसके साथ ।', 'https://quizizz.com/join,https://play.google.com/store/apps/details?id=com.quizizz_mobile&hl=en_IN', 3, 'मुफ्त', 3, 'अंग्रेज़ी', 'HI'),
(58, 'मेघशाला', 'एक पाठ्यक्रम से मिलता , अन्य भाषाओ वाला ऐप जो आपको तैयार पाठ योजनाएं देगा जो आप अपनी कक्षाओं को इंटरनेट के द्वारा लेने के लिए उपयोग कर सकते हैं।', 'https://play.google.com/store/apps/details?id=online.meghshala.app&hl=en_IN,https://play.google.com/store/apps/details?id=online.meghshala.app&hl=en_IN', 1, 'मुफ्त', 1, 'कन्नड़', 'HI'),
(59, 'मेघशाला', 'एक पाठ्यक्रम से मिलता , अन्य भाषाओ वाला ऐप जो आपको तैयार पाठ योजनाएं देगा जो आप अपनी कक्षाओं को इंटरनेट के द्वारा लेने के लिए उपयोग कर सकते हैं।', 'https://play.google.com/store/apps/details?id=online.meghshala.app&hl=en_IN,https://play.google.com/store/apps/details?id=online.meghshala.app&hl=en_IN', 1, 'मुफ्त', 1, 'हिंदी', 'HI'),
(60, 'मेघशाला', 'एक पाठ्यक्रम से मिलता , अन्य भाषाओ वाला ऐप जो आपको तैयार पाठ योजनाएं देगा जो आप अपनी कक्षाओं को इंटरनेट के द्वारा लेने के लिए उपयोग कर सकते हैं।', 'https://play.google.com/store/apps/details?id=online.meghshala.app&hl=en_IN,https://play.google.com/store/apps/details?id=online.meghshala.app&hl=en_IN', 1, 'मुफ्त', 1, 'अंग्रेजी', 'HI'),
(61, 'मेघशाला', 'एक पाठ्यक्रम से मिलता , अन्य भाषाओ वाला ऐप जो आपको तैयार पाठ योजनाएं देगा जो आप अपनी कक्षाओं को इंटरनेट के द्वारा लेने के लिए उपयोग कर सकते हैं।', 'https://play.google.com/store/apps/details?id=online.meghshala.app&hl=en_IN,https://play.google.com/store/apps/details?id=online.meghshala.app&hl=en_IN', 2, 'मुफ्त', 1, 'कन्नड़', 'HI'),
(62, 'मेघशाला', 'एक पाठ्यक्रम से मिलता , अन्य भाषाओ वाला ऐप जो आपको तैयार पाठ योजनाएं देगा जो आप अपनी कक्षाओं को इंटरनेट के द्वारा लेने के लिए उपयोग कर सकते हैं।', 'https://play.google.com/store/apps/details?id=online.meghshala.app&hl=en_IN,https://play.google.com/store/apps/details?id=online.meghshala.app&hl=en_IN', 2, 'मुफ्त', 1, 'हिंदी', 'HI'),
(63, 'मेघशाला', 'एक पाठ्यक्रम से मिलता , अन्य भाषाओ वाला ऐप जो आपको तैयार पाठ योजनाएं देगा जो आप अपनी कक्षाओं को इंटरनेट के द्वारा लेने के लिए उपयोग कर सकते हैं।', 'https://play.google.com/store/apps/details?id=online.meghshala.app&hl=en_IN,https://play.google.com/store/apps/details?id=online.meghshala.app&hl=en_IN', 2, 'मुफ्त', 1, 'अंग्रेजी', 'HI'),
(64, 'टीसीएस आयन डिजिटल ग्लास रूम', 'एक ऐसा मंच जो आपको अपने छात्रों के साथ लाइव वर्चुअल कक्षाएं लेने में सहयोग देता है। छात्रों को होमवर्क और मूल्यांकन के साथ-साथ अभ्यास परीक्षाएं दे और उन्हें साथ ही साथ हल करें।', 'https://learning.tcsionhub.in//EForms/configuredHtml/1016/65312/Registration.html,https://learning.tcsionhub.in//EForms/configuredHtml/1016/65312/Registration.html', 1, 'मुफ्त', 2, 'अंग्रेज़ी', 'HI'),
(65, 'टीसीएस आयन डिजिटल ग्लास रूम', 'एक ऐसा मंच जो आपको अपने छात्रों के साथ लाइव वर्चुअल कक्षाएं लेने में सहयोग देता है। छात्रों को होमवर्क और मूल्यांकन के साथ-साथ अभ्यास परीक्षाएं दे और उन्हें साथ ही साथ हल करें।', 'https://learning.tcsionhub.in//EForms/configuredHtml/1016/65312/Registration.html,https://learning.tcsionhub.in//EForms/configuredHtml/1016/65312/Registration.html', 3, 'मुफ्त', 2, 'अंग्रेज़ी', 'HI'),
(66, 'निष्ठा', 'निष्ठा एक अप्प है जो स्कूल प्रिंसिपल और शिक्षको की सीखने की क्षमता के निर्माण में सहयोग देता है | यह आधुनिक शिक्षक अभ्यास और ट्रेनिंग डिज़ाइन का उपयोग करता है |', 'https://play.google.com/store/apps/details?id=ncert.ciet.nishtha&hl=en_US,https://itpd.ncert.gov.in//', 2, 'मुफ्त', 3, 'अंग्रेज़ी', 'HI'),
(67, 'आईडीपी एडटेक आईआईटी बॉम्बे', 'डिजिटल शिक्षण और अध्ययन के लिए संक्रमण में शिक्षकों की सहायता और समर्थन करने के लिए सरल प्रौद्योगिकी उपकरणों और कैसे-करें वीडियो का भंडार।', 'http://www.et.iitb.ac.in/online-Teaching.html,http://www.et.iitb.ac.in/online-Teaching.html', 1, 'मुफ्त', 1, 'अंग्रेज़ी', 'HI'),
(68, 'आईडीपी एडटेक आईआईटी बॉम्बे', 'डिजिटल शिक्षण और अध्ययन के लिए संक्रमण में शिक्षकों की सहायता और समर्थन करने के लिए सरल प्रौद्योगिकी उपकरणों और कैसे-करें वीडियो का भंडार।', 'http://www.et.iitb.ac.in/online-Teaching.html,http://www.et.iitb.ac.in/online-Teaching.html', 3, 'मुफ्त', 1, 'अंग्रेज़ी', 'HI'),
(69, 'ChalkLit', 'ChalkLit is a free app for teachers to keep themselves updated of the latest pedagogical techniques and methods to teach complex concepts to students.', 'https://play.google.com/store/apps/details?id=com.chalklit.learning', 2, 'Free', 2, 'English', 'EN'),
(70, 'ChalkLit', 'ChalkLit is a free app for teachers to keep themselves updated of the latest pedagogical techniques and methods to teach complex concepts to students.', 'https://play.google.com/store/apps/details?id=com.chalklit.learning', 2, 'Free', 2, 'Hindi', 'EN'),
(71, 'ChalkLit', 'ChalkLit is a free app for teachers to keep themselves updated of the latest pedagogical techniques and methods to teach complex concepts to students.', 'https://play.google.com/store/apps/details?id=com.chalklit.learning', 2, 'Free', 2, 'Odia', 'EN'),
(72, 'Firki', 'Firki is an online teacher education platform that contains 200+ courses, live interaction with experts through webinars, 2000+ online learning & teaching resources with several partner organizations, and space for teachers to form their own online learning circles.', 'https://play.google.com/store/apps/details?id=org.firki.mobile', 1, 'Free', 2, 'English', 'EN'),
(73, 'Firki', 'Firki is an online teacher education platform that contains 200+ courses, live interaction with experts through webinars, 2000+ online learning & teaching resources with several partner organizations, and space for teachers to form their own online learning circles.', 'https://play.google.com/store/apps/details?id=org.firki.mobile', 1, 'Free', 2, 'Hindi', 'EN'),
(74, 'Firki', 'Firki is an online teacher education platform that contains 200+ courses, live interaction with experts through webinars, 2000+ online learning & teaching resources with several partner organizations, and space for teachers to form their own online learning circles.', 'https://play.google.com/store/apps/details?id=org.firki.mobile', 1, 'Free', 2, 'Telugu', 'EN'),
(75, 'Firki', 'Firki is an online teacher education platform that contains 200+ courses, live interaction with experts through webinars, 2000+ online learning & teaching resources with several partner organizations, and space for teachers to form their own online learning circles.', 'https://play.google.com/store/apps/details?id=org.firki.mobile', 1, 'Free', 2, 'Tamil', 'EN'),
(76, 'Firki', 'Firki is an online teacher education platform that contains 200+ courses, live interaction with experts through webinars, 2000+ online learning & teaching resources with several partner organizations, and space for teachers to form their own online learning circles.', 'https://play.google.com/store/apps/details?id=org.firki.mobile', 1, 'Free', 2, 'Kannada', 'EN'),
(77, 'Firki', 'Firki is an online teacher education platform that contains 200+ courses, live interaction with experts through webinars, 2000+ online learning & teaching resources with several partner organizations, and space for teachers to form their own online learning circles.', 'https://play.google.com/store/apps/details?id=org.firki.mobile', 1, 'Free', 2, 'Marathi', 'EN'),
(78, 'Firki', 'Firki is an online teacher education platform that contains 200+ courses, live interaction with experts through webinars, 2000+ online learning & teaching resources with several partner organizations, and space for teachers to form their own online learning circles.', 'https://play.google.com/store/apps/details?id=org.firki.mobile', 2, 'Free', 2, 'English', 'EN'),
(79, 'Firki', 'Firki is an online teacher education platform that contains 200+ courses, live interaction with experts through webinars, 2000+ online learning & teaching resources with several partner organizations, and space for teachers to form their own online learning circles.', 'https://play.google.com/store/apps/details?id=org.firki.mobile', 2, 'Free', 2, 'Hindi', 'EN'),
(80, 'Firki', 'Firki is an online teacher education platform that contains 200+ courses, live interaction with experts through webinars, 2000+ online learning & teaching resources with several partner organizations, and space for teachers to form their own online learning circles.', 'https://play.google.com/store/apps/details?id=org.firki.mobile', 2, 'Free', 2, 'Telugu', 'EN'),
(81, 'Firki', 'Firki is an online teacher education platform that contains 200+ courses, live interaction with experts through webinars, 2000+ online learning & teaching resources with several partner organizations, and space for teachers to form their own online learning circles.', 'https://play.google.com/store/apps/details?id=org.firki.mobile', 2, 'Free', 2, 'Tamil', 'EN'),
(82, 'Firki', 'Firki is an online teacher education platform that contains 200+ courses, live interaction with experts through webinars, 2000+ online learning & teaching resources with several partner organizations, and space for teachers to form their own online learning circles.', 'https://play.google.com/store/apps/details?id=org.firki.mobile', 2, 'Free', 2, 'Kannada', 'EN'),
(83, 'Firki', 'Firki is an online teacher education platform that contains 200+ courses, live interaction with experts through webinars, 2000+ online learning & teaching resources with several partner organizations, and space for teachers to form their own online learning circles.', 'https://play.google.com/store/apps/details?id=org.firki.mobile', 2, 'Free', 2, 'Marathi', 'EN'),
(84, 'Chalk Planboard', 'Planboard allows teachers to organize lessons and reduce prep time. Accessible from anywhere, you can plan lessons, align to curriculum sets, and manage your schedule with ease.', 'https://www.chalk.com/planboard/', 1, 'Free', 2, 'English', 'EN'),
(85, 'Gurushala.co.in', 'Provides teachers with an integrated platform for self-paced capacity development, access to varied resources and platform to connect with peer teachers', 'https://gurushala.co/,https://gurushala.co/', 1, 'Free', 1, 'English', 'EN'),
(86, 'Gurushala.co.in', 'Provides teachers with an integrated platform for self-paced capacity development, access to varied resources and platform to connect with peer teachers', 'https://gurushala.co/,https://gurushala.co/', 1, 'Free', 1, 'Hindi', 'EN'),
(87, 'Gurushala.co.in', 'Provides teachers with an integrated platform for self-paced capacity development, access to varied resources and platform to connect with peer teachers', 'https://gurushala.co/,https://gurushala.co/', 1, 'Free', 1, 'Marathi', 'EN'),
(88, 'Gurushala.co.in', 'Provides teachers with an integrated platform for self-paced capacity development, access to varied resources and platform to connect with peer teachers', 'https://gurushala.co/,https://gurushala.co/', 2, 'Free', 1, 'English', 'EN'),
(89, 'Gurushala.co.in', 'Provides teachers with an integrated platform for self-paced capacity development, access to varied resources and platform to connect with peer teachers', 'https://gurushala.co/,https://gurushala.co/', 2, 'Free', 1, 'Hindi', 'EN'),
(90, 'Gurushala.co.in', 'Provides teachers with an integrated platform for self-paced capacity development, access to varied resources and platform to connect with peer teachers', 'https://gurushala.co/,https://gurushala.co/', 2, 'Free', 1, 'Marathi', 'EN'),
(91, 'Gurushala.co.in', 'Provides teachers with an integrated platform for self-paced capacity development, access to varied resources and platform to connect with peer teachers', 'https://gurushala.co/,https://gurushala.co/', 3, 'Free', 1, 'English', 'EN'),
(92, 'Gurushala.co.in', 'Provides teachers with an integrated platform for self-paced capacity development, access to varied resources and platform to connect with peer teachers', 'https://gurushala.co/,https://gurushala.co/', 3, 'Free', 1, 'Hindi', 'EN'),
(93, 'Gurushala.co.in', 'Provides teachers with an integrated platform for self-paced capacity development, access to varied resources and platform to connect with peer teachers', 'https://gurushala.co/,https://gurushala.co/', 3, 'Free', 1, 'Marathi', 'EN'),
(94, 'चॉक लिट', 'चालकलित अध्यापकों के लिए एक मुफ्त एप्प है, जिसके सहारे वह सीखने और सिखाने  के नई तकनीकियों से वाकिफ हो सकते हैं।', 'https://play.google.com/store/apps/details?id=com.chalklit.learning,https://play.google.com/store/apps/details?id=com.chalklit.learning', 2, 'मुफ्त', 2, 'अंग्रेजी', 'HI'),
(95, 'चॉक लिट', 'चालकलित अध्यापकों के लिए एक मुफ्त एप्प है, जिसके सहारे वह सीखने और सिखाने  के नई तकनीकियों से वाकिफ हो सकते हैं।', 'https://play.google.com/store/apps/details?id=com.chalklit.learning,https://play.google.com/store/apps/details?id=com.chalklit.learning', 2, 'मुफ्त', 2, 'हिंदी', 'HI'),
(96, 'चॉक लिट', 'चालकलित अध्यापकों के लिए एक मुफ्त एप्प है, जिसके सहारे वह सीखने और सिखाने  के नई तकनीकियों से वाकिफ हो सकते हैं।', 'https://play.google.com/store/apps/details?id=com.chalklit.learning,https://play.google.com/store/apps/details?id=com.chalklit.learning', 2, 'मुफ्त', 2, 'ओडिया', 'HI'),
(97, 'फिर्की', 'फ़िरकी एक ऑनलाइन अध्यापक शिक्षा मंच है जिसमें शामिल हैं - 200+ पाठ,वेबिनार के ज़रिये विशेषज्ञों के साथ सीधा संवाद, 2000+ ऑनलाइन सीखने और सिखाने के साधन, और अध्यापकों के स्वयं के लिए ऑनलाइन सिक्षा समूह बनाने के लिए स्थान।', 'https://play.google.com/store/apps/details?id=org.firki.mobile,https://play.google.com/store/apps/details?id=org.firki.mobile', 1, 'मुफ्त', 2, 'अंग्रेजी', 'HI'),
(98, 'फिर्की', 'फ़िरकी एक ऑनलाइन अध्यापक शिक्षा मंच है जिसमें शामिल हैं - 200+ पाठ,वेबिनार के ज़रिये विशेषज्ञों के साथ सीधा संवाद, 2000+ ऑनलाइन सीखने और सिखाने के साधन, और अध्यापकों के स्वयं के लिए ऑनलाइन सिक्षा समूह बनाने के लिए स्थान।', 'https://play.google.com/store/apps/details?id=org.firki.mobile,https://play.google.com/store/apps/details?id=org.firki.mobile', 1, 'मुफ्त', 2, 'हिंदी', 'HI'),
(99, 'फिर्की', 'फ़िरकी एक ऑनलाइन अध्यापक शिक्षा मंच है जिसमें शामिल हैं - 200+ पाठ,वेबिनार के ज़रिये विशेषज्ञों के साथ सीधा संवाद, 2000+ ऑनलाइन सीखने और सिखाने के साधन, और अध्यापकों के स्वयं के लिए ऑनलाइन सिक्षा समूह बनाने के लिए स्थान।', 'https://play.google.com/store/apps/details?id=org.firki.mobile,https://play.google.com/store/apps/details?id=org.firki.mobile', 1, 'मुफ्त', 2, 'तमिल', 'HI'),
(100, 'फिर्की', 'फ़िरकी एक ऑनलाइन अध्यापक शिक्षा मंच है जिसमें शामिल हैं - 200+ पाठ,वेबिनार के ज़रिये विशेषज्ञों के साथ सीधा संवाद, 2000+ ऑनलाइन सीखने और सिखाने के साधन, और अध्यापकों के स्वयं के लिए ऑनलाइन सिक्षा समूह बनाने के लिए स्थान।', 'https://play.google.com/store/apps/details?id=org.firki.mobile,https://play.google.com/store/apps/details?id=org.firki.mobile', 1, 'मुफ्त', 2, 'तेलुगु', 'HI'),
(101, 'फिर्की', 'फ़िरकी एक ऑनलाइन अध्यापक शिक्षा मंच है जिसमें शामिल हैं - 200+ पाठ,वेबिनार के ज़रिये विशेषज्ञों के साथ सीधा संवाद, 2000+ ऑनलाइन सीखने और सिखाने के साधन, और अध्यापकों के स्वयं के लिए ऑनलाइन सिक्षा समूह बनाने के लिए स्थान।', 'https://play.google.com/store/apps/details?id=org.firki.mobile,https://play.google.com/store/apps/details?id=org.firki.mobile', 1, 'मुफ्त', 2, 'मराठी', 'HI'),
(102, 'फिर्की', 'फ़िरकी एक ऑनलाइन अध्यापक शिक्षा मंच है जिसमें शामिल हैं - 200+ पाठ,वेबिनार के ज़रिये विशेषज्ञों के साथ सीधा संवाद, 2000+ ऑनलाइन सीखने और सिखाने के साधन, और अध्यापकों के स्वयं के लिए ऑनलाइन सिक्षा समूह बनाने के लिए स्थान।', 'https://play.google.com/store/apps/details?id=org.firki.mobile,https://play.google.com/store/apps/details?id=org.firki.mobile', 1, 'मुफ्त', 2, 'कन्नड़', 'HI'),
(103, 'फिर्की', 'फ़िरकी एक ऑनलाइन अध्यापक शिक्षा मंच है जिसमें शामिल हैं - 200+ पाठ,वेबिनार के ज़रिये विशेषज्ञों के साथ सीधा संवाद, 2000+ ऑनलाइन सीखने और सिखाने के साधन, और अध्यापकों के स्वयं के लिए ऑनलाइन सिक्षा समूह बनाने के लिए स्थान।', 'https://play.google.com/store/apps/details?id=org.firki.mobile,https://play.google.com/store/apps/details?id=org.firki.mobile', 2, 'मुफ्त', 2, 'अंग्रेजी', 'HI'),
(104, 'फिर्की', 'फ़िरकी एक ऑनलाइन अध्यापक शिक्षा मंच है जिसमें शामिल हैं - 200+ पाठ,वेबिनार के ज़रिये विशेषज्ञों के साथ सीधा संवाद, 2000+ ऑनलाइन सीखने और सिखाने के साधन, और अध्यापकों के स्वयं के लिए ऑनलाइन सिक्षा समूह बनाने के लिए स्थान।', 'https://play.google.com/store/apps/details?id=org.firki.mobile,https://play.google.com/store/apps/details?id=org.firki.mobile', 2, 'मुफ्त', 2, 'हिंदी', 'HI'),
(105, 'फिर्की', 'फ़िरकी एक ऑनलाइन अध्यापक शिक्षा मंच है जिसमें शामिल हैं - 200+ पाठ,वेबिनार के ज़रिये विशेषज्ञों के साथ सीधा संवाद, 2000+ ऑनलाइन सीखने और सिखाने के साधन, और अध्यापकों के स्वयं के लिए ऑनलाइन सिक्षा समूह बनाने के लिए स्थान।', 'https://play.google.com/store/apps/details?id=org.firki.mobile,https://play.google.com/store/apps/details?id=org.firki.mobile', 2, 'मुफ्त', 2, 'तमिल', 'HI'),
(106, 'फिर्की', 'फ़िरकी एक ऑनलाइन अध्यापक शिक्षा मंच है जिसमें शामिल हैं - 200+ पाठ,वेबिनार के ज़रिये विशेषज्ञों के साथ सीधा संवाद, 2000+ ऑनलाइन सीखने और सिखाने के साधन, और अध्यापकों के स्वयं के लिए ऑनलाइन सिक्षा समूह बनाने के लिए स्थान।', 'https://play.google.com/store/apps/details?id=org.firki.mobile,https://play.google.com/store/apps/details?id=org.firki.mobile', 2, 'मुफ्त', 2, 'तेलुगु', 'HI'),
(107, 'फिर्की', 'फ़िरकी एक ऑनलाइन अध्यापक शिक्षा मंच है जिसमें शामिल हैं - 200+ पाठ,वेबिनार के ज़रिये विशेषज्ञों के साथ सीधा संवाद, 2000+ ऑनलाइन सीखने और सिखाने के साधन, और अध्यापकों के स्वयं के लिए ऑनलाइन सिक्षा समूह बनाने के लिए स्थान।', 'https://play.google.com/store/apps/details?id=org.firki.mobile,https://play.google.com/store/apps/details?id=org.firki.mobile', 2, 'मुफ्त', 2, 'मराठी', 'HI'),
(108, 'फिर्की', 'फ़िरकी एक ऑनलाइन अध्यापक शिक्षा मंच है जिसमें शामिल हैं - 200+ पाठ,वेबिनार के ज़रिये विशेषज्ञों के साथ सीधा संवाद, 2000+ ऑनलाइन सीखने और सिखाने के साधन, और अध्यापकों के स्वयं के लिए ऑनलाइन सिक्षा समूह बनाने के लिए स्थान।', 'https://play.google.com/store/apps/details?id=org.firki.mobile,https://play.google.com/store/apps/details?id=org.firki.mobile', 2, 'मुफ्त', 2, 'कन्नड़', 'HI'),
(109, 'चाक प्लानबोर्ड', 'प्लानबोर्ड अध्यापकों को पाठ त्यार करने और त्यारी करने का समय कम करने में मदद करता है। इस प्लैटफ़ार्म को कहीं से भी इस्तेमाल किया जा सकता है, और सिक्षक आसानी से अपनी कक्षा के लिए पाठ्यक्रम के अनुसार पाठ त्यार कर सकते हैं।', 'https://www.chalk.com/planboard/,https://www.chalk.com/planboard/', 1, 'मुफ्त', 2, 'अंग्रेज़ी', 'HI'),
(110, 'गुरुशाला', 'गुरुशाला एक एकीकृत मंच है, जिससे अध्यापकों की आत्मनिर्भरता का विकास होता है। इस मंच पर अध्यापक न केवल विभिन्न संसाधनों का प्रयोग कर सकते है, बल्कि अपने सहकर्मी अध्यापकों के साथ भी जुड़ सकते हैं।', 'https://gurushala.co/,https://gurushala.co/,https://gurushala.co/,https://gurushala.co/', 1, 'मुफ्त', 1, 'अंग्रेजी', 'HI'),
(111, 'गुरुशाला', 'गुरुशाला एक एकीकृत मंच है, जिससे अध्यापकों की आत्मनिर्भरता का विकास होता है। इस मंच पर अध्यापक न केवल विभिन्न संसाधनों का प्रयोग कर सकते है, बल्कि अपने सहकर्मी अध्यापकों के साथ भी जुड़ सकते हैं।', 'https://gurushala.co/,https://gurushala.co/,https://gurushala.co/,https://gurushala.co/', 1, 'मुफ्त', 1, 'हिंदी', 'HI'),
(112, 'गुरुशाला', 'गुरुशाला एक एकीकृत मंच है, जिससे अध्यापकों की आत्मनिर्भरता का विकास होता है। इस मंच पर अध्यापक न केवल विभिन्न संसाधनों का प्रयोग कर सकते है, बल्कि अपने सहकर्मी अध्यापकों के साथ भी जुड़ सकते हैं।', 'https://gurushala.co/,https://gurushala.co/,https://gurushala.co/,https://gurushala.co/', 1, 'मुफ्त', 1, 'मराठी', 'HI'),
(113, 'गुरुशाला', 'गुरुशाला एक एकीकृत मंच है, जिससे अध्यापकों की आत्मनिर्भरता का विकास होता है। इस मंच पर अध्यापक न केवल विभिन्न संसाधनों का प्रयोग कर सकते है, बल्कि अपने सहकर्मी अध्यापकों के साथ भी जुड़ सकते हैं।', 'https://gurushala.co/,https://gurushala.co/,https://gurushala.co/,https://gurushala.co/', 2, 'मुफ्त', 1, 'अंग्रेजी', 'HI'),
(114, 'गुरुशाला', 'गुरुशाला एक एकीकृत मंच है, जिससे अध्यापकों की आत्मनिर्भरता का विकास होता है। इस मंच पर अध्यापक न केवल विभिन्न संसाधनों का प्रयोग कर सकते है, बल्कि अपने सहकर्मी अध्यापकों के साथ भी जुड़ सकते हैं।', 'https://gurushala.co/,https://gurushala.co/,https://gurushala.co/,https://gurushala.co/', 2, 'मुफ्त', 1, 'हिंदी', 'HI'),
(115, 'गुरुशाला', 'गुरुशाला एक एकीकृत मंच है, जिससे अध्यापकों की आत्मनिर्भरता का विकास होता है। इस मंच पर अध्यापक न केवल विभिन्न संसाधनों का प्रयोग कर सकते है, बल्कि अपने सहकर्मी अध्यापकों के साथ भी जुड़ सकते हैं।', 'https://gurushala.co/,https://gurushala.co/,https://gurushala.co/,https://gurushala.co/', 2, 'मुफ्त', 1, 'मराठी', 'HI'),
(116, 'गुरुशाला', 'गुरुशाला एक एकीकृत मंच है, जिससे अध्यापकों की आत्मनिर्भरता का विकास होता है। इस मंच पर अध्यापक न केवल विभिन्न संसाधनों का प्रयोग कर सकते है, बल्कि अपने सहकर्मी अध्यापकों के साथ भी जुड़ सकते हैं।', 'https://gurushala.co/,https://gurushala.co/,https://gurushala.co/,https://gurushala.co/', 3, 'मुफ्त', 1, 'अंग्रेजी', 'HI'),
(117, 'गुरुशाला', 'गुरुशाला एक एकीकृत मंच है, जिससे अध्यापकों की आत्मनिर्भरता का विकास होता है। इस मंच पर अध्यापक न केवल विभिन्न संसाधनों का प्रयोग कर सकते है, बल्कि अपने सहकर्मी अध्यापकों के साथ भी जुड़ सकते हैं।', 'https://gurushala.co/,https://gurushala.co/,https://gurushala.co/,https://gurushala.co/', 3, 'मुफ्त', 1, 'हिंदी', 'HI'),
(118, 'गुरुशाला', 'गुरुशाला एक एकीकृत मंच है, जिससे अध्यापकों की आत्मनिर्भरता का विकास होता है। इस मंच पर अध्यापक न केवल विभिन्न संसाधनों का प्रयोग कर सकते है, बल्कि अपने सहकर्मी अध्यापकों के साथ भी जुड़ सकते हैं।', 'https://gurushala.co/,https://gurushala.co/,https://gurushala.co/,https://gurushala.co/', 3, 'मुफ्त', 1, 'मराठी', 'HI');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `TeacherRecords`
--
ALTER TABLE `TeacherRecords`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `TeacherRecords`
--
ALTER TABLE `TeacherRecords`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=119;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
